export const CURRENCIES = [
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "GBP", name: "British Pound Sterling", symbol: "£" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
    { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
    { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    { code: "CNY", name: "Chinese Yuan Renminbi", symbol: "¥" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "MXN", name: "Mexican Peso", symbol: "Mex$" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
    { code: "EGP", name: "Egyptian Pound", symbol: "ج.م" },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪" }
];

export const CURRENCY_SYMBOLS = {
    USD: { name: "US Dollar", symbol: "$" },
    EUR: { name: "Euro", symbol: "€" },
    GBP: { name: "British Pound Sterling", symbol: "£" },
    JPY: { name: "Japanese Yen", symbol: "¥" },
    CHF: { name: "Swiss Franc", symbol: "CHF" },
    CAD: { name: "Canadian Dollar", symbol: "C$" },
    AUD: { name: "Australian Dollar", symbol: "A$" },
    NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
    CNY: { name: "Chinese Yuan Renminbi", symbol: "¥" },
    SGD: { name: "Singapore Dollar", symbol: "S$" },
    HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
    KRW: { name: "South Korean Won", symbol: "₩" },
    INR: { name: "Indian Rupee", symbol: "₹" },
    BRL: { name: "Brazilian Real", symbol: "R$" },
    ZAR: { name: "South African Rand", symbol: "R" },
    MXN: { name: "Mexican Peso", symbol: "Mex$" },
    RUB: { name: "Russian Ruble", symbol: "₽" },
    SEK: { name: "Swedish Krona", symbol: "kr" },
    NOK: { name: "Norwegian Krone", symbol: "kr" },
    DKK: { name: "Danish Krone", symbol: "kr" },
    TRY: { name: "Turkish Lira", symbol: "₺" },
    IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
    PHP: { name: "Philippine Peso", symbol: "₱" },
    THB: { name: "Thai Baht", symbol: "฿" },
    MYR: { name: "Malaysian Ringgit", symbol: "RM" },
    VND: { name: "Vietnamese Dong", symbol: "₫" },
    AED: { name: "UAE Dirham", symbol: "د.إ" },
    SAR: { name: "Saudi Riyal", symbol: "ر.س" },
    EGP: { name: "Egyptian Pound", symbol: "ج.م" },
    ILS: { name: "Israeli New Shekel", symbol: "₪" }
  };